/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\DA\\Desktop\\ipms-project\\ipms-docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2d5f9df8",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d5f9df8").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-60883ef1",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60883ef1").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-9f00de06",
    path: "/guide/add-project.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f00de06").then(next)
    },
  },
  {
    name: "v-b5397986",
    path: "/guide/admin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b5397986").then(next)
    },
  },
  {
    name: "v-2a144a5d",
    path: "/guide/dashboard.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a144a5d").then(next)
    },
  },
  {
    name: "v-f41fe206",
    path: "/guide/directory.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f41fe206").then(next)
    },
  },
  {
    name: "v-79caa286",
    path: "/guide/data-requirements.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79caa286").then(next)
    },
  },
  {
    name: "v-08c679ee",
    path: "/guide/features.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08c679ee").then(next)
    },
  },
  {
    name: "v-0c8305c3",
    path: "/guide/future-plans.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c8305c3").then(next)
    },
  },
  {
    name: "v-da57c2c6",
    path: "/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-da57c2c6").then(next)
    },
  },
  {
    name: "v-78f4c50f",
    path: "/guide/installation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78f4c50f").then(next)
    },
  },
  {
    name: "v-cce0513a",
    path: "/guide/policies.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cce0513a").then(next)
    },
  },
  {
    name: "v-91151b46",
    path: "/guide/processing-status.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-91151b46").then(next)
    },
  },
  {
    name: "v-4e348d7d",
    path: "/guide/profile.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e348d7d").then(next)
    },
  },
  {
    name: "v-410e3bfd",
    path: "/guide/project-profile.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-410e3bfd").then(next)
    },
  },
  {
    name: "v-5d407a5d",
    path: "/guide/project-menu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d407a5d").then(next)
    },
  },
  {
    name: "v-68fdf7e2",
    path: "/guide/projects.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68fdf7e2").then(next)
    },
  },
  {
    name: "v-5db721bd",
    path: "/guide/report-issues.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5db721bd").then(next)
    },
  },
  {
    name: "v-ff859606",
    path: "/guide/roles.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ff859606").then(next)
    },
  },
  {
    name: "v-6e3e903d",
    path: "/guide/settings.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e3e903d").then(next)
    },
  },
  {
    name: "v-2b7f6f95",
    path: "/guide/user-interface.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b7f6f95").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]