/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Investment Programming & Management System",
  "description": "Documentation of the Investment Programming and Management System",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "href": "https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;523;600;700;800&display=swap",
        "rel": "stylesheet",
        "type": "text/css"
      }
    ],
    [
      "script",
      {
        "src": "https://code.iconify.design/1/1.0.6/iconify.min.js",
        "type": "text/javascript"
      }
    ]
  ],
  "pages": [
    {
      "title": "Introduction",
      "frontmatter": {
        "title": "Introduction",
        "author": "Lester Bolotaolo"
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-2d5f9df8",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "Background and Rationale",
          "slug": "background-and-rationale"
        },
        {
          "level": 2,
          "title": "Issues: What went wrong?",
          "slug": "issues-what-went-wrong"
        },
        {
          "level": 2,
          "title": "Solution",
          "slug": "solution"
        }
      ],
      "lastUpdated": "6/22/2020, 8:34:46 PM"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/app-logo-128x128.png",
        "tagline": "Improving the investment programming process one step at a time",
        "actionText": "Quick Start →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Project Management",
            "details": "Manage your Public Investment Program programs and projects in one place"
          },
          {
            "title": "Single Page App",
            "details": "Faster, simpler, user-friendly"
          },
          {
            "title": "Progressive Web App",
            "details": "Installable and can be used offline"
          }
        ],
        "footer": "Made by Mark Lester A. Bolotaolo with ❤️"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-60883ef1",
      "path": "/",
      "lastUpdated": "6/4/2020, 11:41:30 AM"
    },
    {
      "title": "Add Project",
      "frontmatter": {},
      "regularPath": "/guide/add-project.html",
      "relativePath": "guide/add-project.md",
      "key": "v-9f00de06",
      "path": "/guide/add-project.html",
      "headers": [
        {
          "level": 2,
          "title": "Add Project Form",
          "slug": "add-project-form"
        }
      ],
      "lastUpdated": "7/19/2020, 10:10:36 PM"
    },
    {
      "title": "Admin Page",
      "frontmatter": {
        "title": "Admin Page",
        "author": "Lester Bolotaolo",
        "tags": [
          "admin",
          "users",
          "manage users",
          "reviewers",
          "assign role",
          "assign operating unit"
        ]
      },
      "regularPath": "/guide/admin.html",
      "relativePath": "guide/admin.md",
      "key": "v-b5397986",
      "path": "/guide/admin.html",
      "lastUpdated": "6/5/2020, 1:52:09 PM"
    },
    {
      "title": "Dashboard",
      "frontmatter": {
        "title": "Dashboard",
        "tags": [
          "dashboard",
          "shortcuts",
          "summary",
          "activities",
          "exchange rates"
        ]
      },
      "regularPath": "/guide/dashboard.html",
      "relativePath": "guide/dashboard.md",
      "key": "v-2a144a5d",
      "path": "/guide/dashboard.html",
      "headers": [
        {
          "level": 2,
          "title": "Summary",
          "slug": "summary"
        },
        {
          "level": 2,
          "title": "Shortcuts",
          "slug": "shortcuts"
        },
        {
          "level": 2,
          "title": "Activity Feed",
          "slug": "activity-feed"
        },
        {
          "level": 2,
          "title": "Exchange Rates",
          "slug": "exchange-rates"
        }
      ],
      "lastUpdated": "6/4/2020, 11:41:30 AM"
    },
    {
      "title": "Directory",
      "frontmatter": {},
      "regularPath": "/guide/directory.html",
      "relativePath": "guide/directory.md",
      "key": "v-f41fe206",
      "path": "/guide/directory.html",
      "lastUpdated": "6/3/2020, 6:31:31 PM"
    },
    {
      "title": "Data Requirements",
      "frontmatter": {
        "title": "Data Requirements"
      },
      "regularPath": "/guide/data-requirements.html",
      "relativePath": "guide/data-requirements.md",
      "key": "v-79caa286",
      "path": "/guide/data-requirements.html",
      "headers": [
        {
          "level": 2,
          "title": "Basic Information",
          "slug": "basic-information"
        },
        {
          "level": 2,
          "title": "Technical Readiness",
          "slug": "technical-readiness"
        },
        {
          "level": 2,
          "title": "Financial Information",
          "slug": "financial-information"
        },
        {
          "level": 2,
          "title": "Investment Requirements",
          "slug": "investment-requirements"
        },
        {
          "level": 2,
          "title": "PAP Status",
          "slug": "pap-status"
        }
      ],
      "lastUpdated": "6/23/2020, 5:50:50 PM"
    },
    {
      "title": "Features",
      "frontmatter": {
        "title": "Features",
        "author": "Lester Bolotaolo",
        "tags": [
          "features",
          "open source",
          "good documentation",
          "lightweight",
          "responsive"
        ]
      },
      "regularPath": "/guide/features.html",
      "relativePath": "guide/features.md",
      "key": "v-08c679ee",
      "path": "/guide/features.html",
      "headers": [
        {
          "level": 2,
          "title": "Project Management",
          "slug": "project-management"
        },
        {
          "level": 2,
          "title": "Good Documentation",
          "slug": "good-documentation"
        },
        {
          "level": 2,
          "title": "Open-Source",
          "slug": "open-source"
        },
        {
          "level": 2,
          "title": "Lightweight",
          "slug": "lightweight"
        },
        {
          "level": 2,
          "title": "Single Page Application",
          "slug": "single-page-application"
        },
        {
          "level": 2,
          "title": "Responsive",
          "slug": "responsive"
        }
      ],
      "lastUpdated": "6/4/2020, 8:51:10 AM"
    },
    {
      "title": "Future Plans",
      "frontmatter": {},
      "regularPath": "/guide/future-plans.html",
      "relativePath": "guide/future-plans.md",
      "key": "v-0c8305c3",
      "path": "/guide/future-plans.html",
      "headers": [
        {
          "level": 2,
          "title": "Report Generation",
          "slug": "report-generation"
        },
        {
          "level": 2,
          "title": "Automated Prioritization",
          "slug": "automated-prioritization"
        },
        {
          "level": 2,
          "title": "Integration with Other Databases/Systems in the DA",
          "slug": "integration-with-other-databases-systems-in-the-da"
        },
        {
          "level": 2,
          "title": "Support for next PIP Updating",
          "slug": "support-for-next-pip-updating"
        },
        {
          "level": 2,
          "title": "Others",
          "slug": "others"
        }
      ],
      "lastUpdated": "6/3/2020, 6:31:31 PM"
    },
    {
      "title": "Getting Started",
      "frontmatter": {
        "title": "Getting Started",
        "author": "Lester Bolotaolo",
        "lang": "en-US",
        "description": "Getting started with the IPMS",
        "date": "2020-06-02T09:04:00.000Z",
        "tags": [
          "login",
          "password",
          "forgot password",
          "reset password",
          "verify email",
          "create account",
          "sign up"
        ]
      },
      "regularPath": "/guide/getting-started.html",
      "relativePath": "guide/getting-started.md",
      "key": "v-da57c2c6",
      "path": "/guide/getting-started.html",
      "headers": [
        {
          "level": 2,
          "title": "Accessing the System",
          "slug": "accessing-the-system"
        },
        {
          "level": 2,
          "title": "Getting an Account",
          "slug": "getting-an-account"
        },
        {
          "level": 2,
          "title": "Logging in to the IPMS",
          "slug": "logging-in-to-the-ipms"
        },
        {
          "level": 3,
          "title": "First Time",
          "slug": "first-time"
        },
        {
          "level": 3,
          "title": "Succeeding",
          "slug": "succeeding"
        },
        {
          "level": 2,
          "title": "Verifying your email address",
          "slug": "verifying-your-email-address"
        },
        {
          "level": 2,
          "title": "Changing your password",
          "slug": "changing-your-password"
        },
        {
          "level": 2,
          "title": "Recovering Forgotten Password",
          "slug": "recovering-forgotten-password"
        },
        {
          "level": 2,
          "title": "Next Steps",
          "slug": "next-steps"
        }
      ],
      "lastUpdated": "7/19/2020, 10:10:36 PM"
    },
    {
      "title": "Installation",
      "frontmatter": {
        "title": "Installation",
        "author": "Lester Bolotaolo",
        "tags": [
          "install",
          "pwa",
          "desktop",
          "mac",
          "android",
          "offline"
        ]
      },
      "regularPath": "/guide/installation.html",
      "relativePath": "guide/installation.md",
      "key": "v-78f4c50f",
      "path": "/guide/installation.html",
      "headers": [
        {
          "level": 2,
          "title": "Requirements",
          "slug": "requirements"
        },
        {
          "level": 2,
          "title": "Install PWA on desktop",
          "slug": "install-pwa-on-desktop"
        },
        {
          "level": 2,
          "title": "Install PWA on Android device",
          "slug": "install-pwa-on-android-device"
        },
        {
          "level": 2,
          "title": "Uninstall",
          "slug": "uninstall"
        }
      ],
      "lastUpdated": "6/4/2020, 5:32:37 PM"
    },
    {
      "title": "Policies",
      "frontmatter": {
        "title": "Policies",
        "author": "Lester Bolotaolo",
        "tags": [
          "roles",
          "admin",
          "superadmin",
          "reviewer",
          "encoder",
          "viewer",
          "guest"
        ]
      },
      "regularPath": "/guide/policies.html",
      "relativePath": "guide/policies.md",
      "key": "v-cce0513a",
      "path": "/guide/policies.html",
      "headers": [
        {
          "level": 2,
          "title": "Credentials",
          "slug": "credentials"
        }
      ],
      "lastUpdated": "6/5/2020, 1:52:09 PM"
    },
    {
      "title": "Understanding Processing Status",
      "frontmatter": {
        "title": "Understanding Processing Status"
      },
      "regularPath": "/guide/processing-status.html",
      "relativePath": "guide/processing-status.md",
      "key": "v-91151b46",
      "path": "/guide/processing-status.html",
      "lastUpdated": "7/19/2020, 10:10:36 PM"
    },
    {
      "title": "Profile",
      "frontmatter": {},
      "regularPath": "/guide/profile.html",
      "relativePath": "guide/profile.md",
      "key": "v-4e348d7d",
      "path": "/guide/profile.html",
      "headers": [
        {
          "level": 2,
          "title": "Updating Profile",
          "slug": "updating-profile"
        },
        {
          "level": 2,
          "title": "Upload/Change Avatar",
          "slug": "upload-change-avatar"
        }
      ],
      "lastUpdated": "6/3/2020, 9:36:57 AM"
    },
    {
      "title": "Project Profile",
      "frontmatter": {},
      "regularPath": "/guide/project-profile.html",
      "relativePath": "guide/project-profile.md",
      "key": "v-410e3bfd",
      "path": "/guide/project-profile.html",
      "lastUpdated": "7/19/2020, 10:10:36 PM"
    },
    {
      "title": "Project Menu",
      "frontmatter": {},
      "regularPath": "/guide/project-menu.html",
      "relativePath": "guide/project-menu.md",
      "key": "v-5d407a5d",
      "path": "/guide/project-menu.html",
      "headers": [
        {
          "level": 2,
          "title": "View Project",
          "slug": "view-project"
        },
        {
          "level": 2,
          "title": "Update Project",
          "slug": "update-project"
        },
        {
          "level": 2,
          "title": "Transfer Project",
          "slug": "transfer-project"
        },
        {
          "level": 2,
          "title": "Share Project",
          "slug": "share-project"
        },
        {
          "level": 2,
          "title": "Delete Project",
          "slug": "delete-project"
        },
        {
          "level": 2,
          "title": "Download Project",
          "slug": "download-project"
        }
      ],
      "lastUpdated": "7/19/2020, 10:10:36 PM"
    },
    {
      "title": "Project Manager",
      "frontmatter": {
        "title": "Project Manager",
        "tags": [
          "add project",
          "update project",
          "delete project",
          "view project",
          "transfer project",
          "endorse project",
          "review project",
          "validate project",
          "endorse project",
          "monitor project",
          "share project",
          "search project"
        ]
      },
      "regularPath": "/guide/projects.html",
      "relativePath": "guide/projects.md",
      "key": "v-68fdf7e2",
      "path": "/guide/projects.html",
      "headers": [
        {
          "level": 2,
          "title": "Projects Directory",
          "slug": "projects-directory"
        },
        {
          "level": 2,
          "title": "View Projects by Status",
          "slug": "view-projects-by-status"
        },
        {
          "level": 2,
          "title": "Project Submission Flow",
          "slug": "project-submission-flow"
        },
        {
          "level": 2,
          "title": "Add Project",
          "slug": "add-project"
        },
        {
          "level": 2,
          "title": "View Project",
          "slug": "view-project"
        },
        {
          "level": 2,
          "title": "Update Project",
          "slug": "update-project"
        },
        {
          "level": 2,
          "title": "Finalize Project",
          "slug": "finalize-project"
        },
        {
          "level": 2,
          "title": "Endorse Project",
          "slug": "endorse-project"
        },
        {
          "level": 2,
          "title": "Validate Project",
          "slug": "validate-project"
        },
        {
          "level": 2,
          "title": "Review Project",
          "slug": "review-project"
        },
        {
          "level": 2,
          "title": "Accept Project",
          "slug": "accept-project"
        },
        {
          "level": 2,
          "title": "Approve Project",
          "slug": "approve-project"
        },
        {
          "level": 2,
          "title": "Transfer Project",
          "slug": "transfer-project"
        },
        {
          "level": 2,
          "title": "Delete Project",
          "slug": "delete-project"
        },
        {
          "level": 2,
          "title": "Monitor Project",
          "slug": "monitor-project"
        },
        {
          "level": 2,
          "title": "Share Project (enhancement)",
          "slug": "share-project-enhancement"
        },
        {
          "level": 2,
          "title": "Search Project",
          "slug": "search-project"
        }
      ],
      "lastUpdated": "6/22/2020, 8:34:46 PM"
    },
    {
      "title": "Report Issues",
      "frontmatter": {
        "title": "Report Issues",
        "author": "Lester Bolotaolo",
        "tags": [
          "errors",
          "issues",
          "requests",
          "feature request"
        ]
      },
      "regularPath": "/guide/report-issues.html",
      "relativePath": "guide/report-issues.md",
      "key": "v-5db721bd",
      "path": "/guide/report-issues.html",
      "lastUpdated": "6/5/2020, 11:41:33 AM"
    },
    {
      "title": "Roles",
      "frontmatter": {
        "title": "Roles",
        "author": "Lester Bolotaolo"
      },
      "regularPath": "/guide/roles.html",
      "relativePath": "guide/roles.md",
      "key": "v-ff859606",
      "path": "/guide/roles.html",
      "headers": [
        {
          "level": 2,
          "title": "Roles Definition",
          "slug": "roles-definition"
        },
        {
          "level": 2,
          "title": "Users",
          "slug": "users"
        },
        {
          "level": 2,
          "title": "Assign Role",
          "slug": "assign-role"
        },
        {
          "level": 2,
          "title": "Assign Operating Unit",
          "slug": "assign-operating-unit"
        }
      ],
      "lastUpdated": "6/5/2020, 1:52:09 PM"
    },
    {
      "title": "Settings Page",
      "frontmatter": {
        "title": "Settings Page",
        "author": "Lester Bolotaolo",
        "tags": [
          "compact mode",
          "dark mode",
          "settings",
          "reset app"
        ]
      },
      "regularPath": "/guide/settings.html",
      "relativePath": "guide/settings.md",
      "key": "v-6e3e903d",
      "path": "/guide/settings.html",
      "headers": [
        {
          "level": 2,
          "title": "Compact View",
          "slug": "compact-view"
        },
        {
          "level": 2,
          "title": "Dark Mode",
          "slug": "dark-mode"
        },
        {
          "level": 2,
          "title": "Reset Application",
          "slug": "reset-application"
        }
      ],
      "lastUpdated": "6/3/2020, 6:31:31 PM"
    },
    {
      "title": "User Interface",
      "frontmatter": {},
      "regularPath": "/guide/user-interface.html",
      "relativePath": "guide/user-interface.md",
      "key": "v-2b7f6f95",
      "path": "/guide/user-interface.html",
      "headers": [
        {
          "level": 2,
          "title": "Parts of the Interface",
          "slug": "parts-of-the-interface"
        },
        {
          "level": 2,
          "title": "The User Interface",
          "slug": "the-user-interface"
        },
        {
          "level": 2,
          "title": "Header",
          "slug": "header"
        },
        {
          "level": 2,
          "title": "Sidebar",
          "slug": "sidebar"
        },
        {
          "level": 2,
          "title": "Footer",
          "slug": "footer"
        }
      ],
      "lastUpdated": "7/19/2020, 10:10:36 PM"
    }
  ],
  "themeConfig": {
    "logo": "/app-logo-128x128.png",
    "repo": "mlab817/ipms-docs",
    "repoLabel": "Contribute",
    "editLinks": true,
    "docsDir": "docs",
    "docsRepo": "mlab817/ipms-docs",
    "docsBranch": "master",
    "lastUpdated": "Last Updated",
    "editLinkText": "Edit this page on GitHub",
    "smoothScroll": true,
    "nav": [
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "App",
        "link": "https://da-ipms2020.web.app"
      }
    ],
    "sidebar": {
      "/guide/": [
        {
          "title": "Guide",
          "collapsable": false,
          "children": [
            "",
            "features",
            "getting-started",
            "installation",
            "user-interface",
            "dashboard",
            "profile",
            "roles",
            "settings",
            "policies",
            "report-issues"
          ]
        },
        {
          "title": "Projects",
          "collapsable": true,
          "children": [
            "add-project",
            "processing-status",
            "project-menu",
            "project-profile",
            "data-requirements"
          ]
        },
        {
          "title": "Ways Forward",
          "collapsable": true,
          "children": [
            "future-plans"
          ]
        }
      ]
    }
  }
}