version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - checkout
      - restore_cache:
          key: 'v1-yarn-{{ checksum "yarn.lock" }}'
      - run: yarn install
      - save_cache:
          key: 'v1-yarn-{{ checksum "yarn.lock" }}'
          paths:
            - ./node_modules
      - run: yarn build
  deploy:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - deploy
      - run: firebase deploy --only hosting

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build