version: 2

jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: yarn install
            - save_cache:
                  key: v1-dependencies-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Build
                  command: yarn build
            - run:
                  name: Firebase Deploy
                  command: ln -s ./node_modules/.bin/firebase . && firebase deploy --token "$FIREBASE_TOKEN" --only hosting